export type BusinessKind = 'bakery'|'gadgets'|'staycation'|'general';
export type BusinessProfile = {kind:BusinessKind;name:string};
export const BUSINESS_THEMES = {
 bakery:{label:'Bakery & food',description:'Breads, pastries, cakes, and other food made to order.',preparation:'Kitchen',prepareDescription:'Orders to prepare, by due date.',prepareVerb:'prepare',catalog:'Product catalog',customer:'Customers',list:'To bake today',example:'Ate, pa-order 2 dozen cheese pandesal bukas, pickup 8am po.',emoji:'🥐'},
 gadgets:{label:'Gadget shop',description:'Devices, accessories, and repair or setup services.',preparation:'Dispatch',prepareDescription:'Orders to pack and hand off, by due date.',prepareVerb:'pack',catalog:'Products & accessories',customer:'Customers',list:'To pack today',example:'Pa-order po 2 USB-C cables, pickup bukas 10am.',emoji:'📱'},
 staycation:{label:'Staycation',description:'Reservations, guest stays, and add-on services.',preparation:'Bookings',prepareDescription:'Pending requests, confirmed stays, arrivals, and departures.',prepareVerb:'review',catalog:'Stays, services & extras',customer:'Guests',list:'Guest requests today',example:'Available po ba October 15–17 for 4 guests?',emoji:'🏡'},
 general:{label:'General business',description:'Any products or services sold through chat.',preparation:'Fulfillment',prepareDescription:'Work waiting, in progress, and ready, by due date.',prepareVerb:'prepare',catalog:'Products & services',customer:'Customers',list:'To prepare today',example:'Pa-order po 2 pieces, pickup bukas 10am.',emoji:'🛍️'},
} as const;

export const CATALOG_CONFIG = {
 bakery:{title:'Your bakery menu',description:'Breads, pastries, cakes, and food services you offer.',add:'Add menu item',name:'Menu item name',categories:['Bread','Pastry','Cookies','Cake','Food services','Other'],units:['piece','cake','loaf','tray','box','service','session'],defaultUnit:'piece',types:['product','service'],example:'cheesy pandesal, cheese bread'},
 gadgets:{title:'Your products & services',description:'Devices, accessories, and services available in your shop.',add:'Add product or service',name:'Product or service name',categories:['Phones','Computers','Accessories','Audio','Services','Other'],units:['unit','piece','set','box','service','session'],defaultUnit:'unit',types:['product','service'],example:'type c cable, charging cable'},
 staycation:{title:'Your stays, services & extras',description:'List accommodations, guest extras, and services. Set nightly rates for individual bookable rooms and manage their reservation dates.',add:'Add stay or service',name:'Accommodation, extra, or service name',categories:['Accommodations','Guest extras','Services','Packages','Other'],units:['night','stay','guest','service','session','set','piece'],defaultUnit:'night',types:['accommodation','service','product'],example:'studio unit, studio room'},
 general:{title:'Your products & services',description:'Everything your business offers, with your own prices and customer names.',add:'Add offering',name:'Offering name',categories:['Products','Services','Packages','Other'],units:['piece','unit','set','box','service','session'],defaultUnit:'piece',types:['product','service'],example:'Names customers use'},
} as const;
